name: 'Zip Release'
author: 'TheDoctor0'
branding:
  icon: 'archive'
  color: 'yellow'
description: 'Make an archive from specified files and directories as workflow action'
inputs:
  filename:
    description: 'Filename for archive'
    required: true
    default: 'release.zip'
  path:
    description: 'Base path for archive files'
    default: '.'
    required: false
  directory:
    description: 'Working directory before zipping'
    default: '.'
    required: false
  exclusions:
    description: 'List of excluded files / directories'
    default: ''
    required: false
  recursive_exclusions:
    description: 'List of excluded files / directories with recursive wildcards (only applies on Windows with `zip` type)'
    default: ''
    required: false
  custom:
    description: 'Provide any custom parameters to the command'
    default: ''
    required: false
  type:
    description: 'Tool to use for archiving'
    default: 'zip'
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      env:
        INPUT_FILENAME: ${{ inputs.filename }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_EXCLUSIONS: ${{ inputs.exclusions }}
        INPUT_RECURSIVE_EXCLUSIONS: ${{ inputs.recursive_exclusions }}
        INPUT_CUSTOM: ${{ inputs.custom }}
        INPUT_TYPE: ${{ inputs.type }}
      run: $GITHUB_ACTION_PATH/entrypoint.sh

